#ifndef MODULE_CONFIG_H
#define MODULE_CONFIG_H

#define ARDUQUARIUM_DEBUG_BUILD
//#define ARDUQUARIUM_RELEASE_BUILD

#define ARDUQUARIUM_WATER_SENSOR_PIN A0
#define ARDUQUARIUM_PH4502C_PH_PIN A1
#define ARDUQUARIUM_LM35DZ_PIN A2

#define ARDUQUARIUM_PH_LEVEL_PH_CALIBRATION 14.8
#define ARDUQUARIUM_PH_LEVEL_READ_INTERVAL 10
#define ARDUQUARIUM_PH_LEVEL_READING_COUNT 10

#endif