#ifndef MODULE_CONFIG_H
#define MODULE_CONFIG_H

#define ARDUQUARIUM_DEBUG_BUILD
//#define ARDUQUARIUM_RELEASE_BUILD

#define PH_LEVEL_READ_INTERVAL 10
#define PH_LEVEL_READING_COUNT 10

#define PH4502C_TEMPERATURE_PIN A0
#define PH4502C_PH_PIN A1

#endif